import { Head, router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import { UserPlusIcon, ClipboardDocumentListIcon, PhotoIcon, PencilSquareIcon, TrashIcon } from '@heroicons/react/24/outline';
import AdminLayout from '../../Layouts/AdminLayout';
import { Badge, Card, PageTitle, money } from '../../Components/AdminUi';

const blank={nombre:'',apellido:'',correo:'',telefono:'',numero_empleado:'',cargo:'Subadministrador',comision_porcentaje:0,permisos:['dashboard.view','events.view','events.create','events.edit','events.publish','tickets.view','stock.view','qr.validate','profile.update'],password:'',foto_perfil:null};

export default function Staff({staff=[],tasks=[],permissionOptions=[]}){
 const form=useForm(blank); const edit=useForm(blank); const task=useForm({titulo:'',descripcion:'',prioridad:'media',vence_en:''});
 const[selected,setSelected]=useState(null); const[taskUser,setTaskUser]=useState(null); const[q,setQ]=useState('');
 const rows=useMemo(()=>staff.filter(s=>`${s.fullName} ${s.email} ${s.employeeNumber||''} ${s.position||''}`.toLowerCase().includes(q.toLowerCase())),[staff,q]);
 const togglePerm=(f,key)=>{const cur=f.data.permisos||[];f.setData('permisos',cur.includes(key)?cur.filter(x=>x!==key):[...cur,key])};
 const openEdit=(s)=>{setSelected(s);edit.setData({nombre:s.name,apellido:s.lastName,correo:s.email,telefono:s.phone||'',numero_empleado:s.employeeNumber||'',cargo:s.position||'',comision_porcentaje:s.commissionPercent||0,permisos:s.permissions||[],password:'',foto_perfil:null})};
 return <AdminLayout><Head title="Empleados"/><div className="mx-auto max-w-[1600px] p-5 sm:p-8"><PageTitle title="Empleados y subadministradores" description="Solo el administrador principal puede crear empleados. Define permisos, comisión, datos de perfil y tareas. Los empleados no pueden registrarse por su cuenta." actions={<button onClick={()=>document.getElementById('nuevo-empleado')?.scrollIntoView({behavior:'smooth'})} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-black text-white"><UserPlusIcon className="h-5 w-5"/>Contratar empleado</button>}/>
 <Card className="mt-6 p-6" id="nuevo-empleado"><h2 className="text-lg font-black">Registrar nuevo empleado</h2><form onSubmit={e=>{e.preventDefault();form.post('/admin/empleados',{forceFormData:true,preserveScroll:true,onSuccess:()=>form.setData(blank)})}} className="mt-5 grid gap-4 lg:grid-cols-4"><Field label="Nombre"><input className="input" value={form.data.nombre} onChange={e=>form.setData('nombre',e.target.value)}/></Field><Field label="Apellido"><input className="input" value={form.data.apellido} onChange={e=>form.setData('apellido',e.target.value)}/></Field><Field label="Correo"><input type="email" className="input" value={form.data.correo} onChange={e=>form.setData('correo',e.target.value)}/></Field><Field label="Teléfono"><input className="input" value={form.data.telefono} onChange={e=>form.setData('telefono',e.target.value)}/></Field><Field label="N.º empleado"><input className="input" value={form.data.numero_empleado} onChange={e=>form.setData('numero_empleado',e.target.value)}/></Field><Field label="Cargo"><input className="input" value={form.data.cargo} onChange={e=>form.setData('cargo',e.target.value)}/></Field><Field label="Comisión %"><input type="number" step="0.01" className="input" value={form.data.comision_porcentaje} onChange={e=>form.setData('comision_porcentaje',e.target.value)}/></Field><Field label="Contraseña inicial"><input type="password" className="input" value={form.data.password} onChange={e=>form.setData('password',e.target.value)}/></Field><Field label="Foto"><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-violet-300 bg-violet-50 px-4 py-3 text-sm font-black text-violet-700"><PhotoIcon className="h-5 w-5"/>Elegir foto<input type="file" accept="image/*" className="hidden" onChange={e=>form.setData('foto_perfil',e.target.files?.[0]||null)}/></label></Field><div className="lg:col-span-3"><p className="mb-2 text-xs font-black uppercase text-slate-500">Permisos</p><div className="flex flex-wrap gap-2">{permissionOptions.map(p=><label key={p.key} className={`cursor-pointer rounded-full border px-3 py-2 text-xs font-bold ${form.data.permisos.includes(p.key)?'border-violet-300 bg-violet-100 text-violet-700':'border-slate-200 text-slate-500'}`}><input type="checkbox" checked={form.data.permisos.includes(p.key)} onChange={()=>togglePerm(form,p.key)} className="mr-2"/>{p.label}</label>)}</div></div><div className="lg:col-span-4">{Object.values(form.errors).map((e,i)=><p key={i} className="text-sm font-bold text-red-600">{e}</p>)}<button className="mt-2 rounded-xl bg-violet-600 px-6 py-3 font-black text-white">Crear empleado</button></div></form></Card>
 <Card className="mt-6 p-5"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar empleado..." className="w-full rounded-xl border-slate-200"/></Card>
 <div className="mt-5 grid gap-5 xl:grid-cols-2">{rows.map((s,i)=><Card key={s.id} className="p-5"><div className="flex items-start gap-4">{s.photo?<img src={s.photo} className="h-16 w-16 rounded-2xl object-cover"/>:<div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-100 text-xl font-black text-violet-700">{s.fullName.slice(0,2).toUpperCase()}</div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-lg font-black text-slate-900">{s.fullName}</h3><p className="text-sm text-slate-500">{s.position} · {s.employeeNumber||'Sin número'}</p></div><Badge tone={s.active?'green':'red'}>{s.active?'Activo':'Inactivo'}</Badge></div><p className="mt-2 text-xs text-slate-400">{s.email} · {s.phone||'sin teléfono'}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Mini label="Eventos" value={s.events}/><Mini label="Entradas" value={s.tickets}/><Mini label="Ventas" value={s.sales}/><Mini label="Ingresos" value={money(s.revenue)}/><Mini label="Comisión" value={money(s.commission)}/></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>openEdit(s)} className="inline-flex items-center gap-2 rounded-xl border border-violet-200 px-4 py-2 text-xs font-black text-violet-700"><PencilSquareIcon className="h-4 w-4"/>Editar/permisos</button>{s.role==='subadministrador'&&<button onClick={()=>setTaskUser(s)} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 px-4 py-2 text-xs font-black text-blue-700"><ClipboardDocumentListIcon className="h-4 w-4"/>Asignar tarea</button>}<button onClick={()=>router.patch(`/admin/empleados/${s.id}/estado`,{}, {preserveScroll:true})} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black text-slate-600">{s.active?'Desactivar':'Activar'}</button>{s.role==='subadministrador'&&<button type="button" onClick={()=>{if(window.confirm(`¿Eliminar a ${s.fullName}?\n\nYa no podrá iniciar sesión y desaparecerá de la lista de empleados. El historial de eventos, ventas y comisiones se conservará.`)){router.delete(`/admin/empleados/${s.id}`,{preserveScroll:true})}}} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-xs font-black text-red-600 transition hover:bg-red-100"><TrashIcon className="h-4 w-4"/>Eliminar</button>}</div></Card>)}</div>
 <Card className="mt-6 overflow-hidden"><div className="border-b p-6"><h2 className="text-lg font-black">Tareas del equipo</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th className="px-6 py-4">Tarea</th><th>Asignado a</th><th>Prioridad</th><th>Estado</th><th>Vence</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id} className="border-t"><td className="px-6 py-4"><p className="font-black">{t.title}</p><p className="text-xs text-slate-400">{t.description}</p></td><td>{t.assignee}</td><td><Badge tone={t.priority==='alta'?'red':t.priority==='media'?'amber':'blue'}>{t.priority}</Badge></td><td>{t.status}</td><td>{t.due||'—'}</td></tr>)}</tbody></table></div></Card>
 {selected&&<Modal title={`Editar ${selected.fullName}`} onClose={()=>setSelected(null)}><form onSubmit={e=>{e.preventDefault();edit.post(`/admin/empleados/${selected.id}`,{forceFormData:true,preserveScroll:true,onSuccess:()=>setSelected(null)})}} className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><input className="input" value={edit.data.nombre} onChange={e=>edit.setData('nombre',e.target.value)}/></Field><Field label="Apellido"><input className="input" value={edit.data.apellido} onChange={e=>edit.setData('apellido',e.target.value)}/></Field><Field label="Correo"><input className="input" value={edit.data.correo} onChange={e=>edit.setData('correo',e.target.value)}/></Field><Field label="Teléfono"><input className="input" value={edit.data.telefono} onChange={e=>edit.setData('telefono',e.target.value)}/></Field><Field label="N.º empleado"><input className="input" value={edit.data.numero_empleado} onChange={e=>edit.setData('numero_empleado',e.target.value)}/></Field><Field label="Cargo"><input className="input" value={edit.data.cargo} onChange={e=>edit.setData('cargo',e.target.value)}/></Field><Field label="Comisión %"><input type="number" step="0.01" className="input" value={edit.data.comision_porcentaje} onChange={e=>edit.setData('comision_porcentaje',e.target.value)}/></Field><Field label="Nueva contraseña (opcional)"><input type="password" className="input" value={edit.data.password} onChange={e=>edit.setData('password',e.target.value)}/></Field><div className="sm:col-span-2"><p className="mb-2 text-xs font-black uppercase text-slate-500">Permisos</p><div className="flex flex-wrap gap-2">{permissionOptions.map(p=><label key={p.key} className={`cursor-pointer rounded-full border px-3 py-2 text-xs font-bold ${edit.data.permisos.includes(p.key)?'border-violet-300 bg-violet-100 text-violet-700':'border-slate-200'}`}><input type="checkbox" checked={edit.data.permisos.includes(p.key)} onChange={()=>togglePerm(edit,p.key)} className="mr-2"/>{p.label}</label>)}</div></div><button className="rounded-xl bg-violet-600 px-5 py-3 font-black text-white sm:col-span-2">Guardar cambios</button></form></Modal>}
 {taskUser&&<Modal title={`Asignar tarea a ${taskUser.fullName}`} onClose={()=>setTaskUser(null)}><form onSubmit={e=>{e.preventDefault();task.post(`/admin/empleados/${taskUser.id}/tareas`,{preserveScroll:true,onSuccess:()=>{setTaskUser(null);task.reset();}})}} className="space-y-4"><Field label="Título"><input className="input" value={task.data.titulo} onChange={e=>task.setData('titulo',e.target.value)}/></Field><Field label="Descripción"><textarea className="input" value={task.data.descripcion} onChange={e=>task.setData('descripcion',e.target.value)}/></Field><Field label="Prioridad"><select className="input" value={task.data.prioridad} onChange={e=>task.setData('prioridad',e.target.value)}><option>baja</option><option>media</option><option>alta</option></select></Field><Field label="Vence"><input type="datetime-local" className="input" value={task.data.vence_en} onChange={e=>task.setData('vence_en',e.target.value)}/></Field><button className="w-full rounded-xl bg-blue-600 px-5 py-3 font-black text-white">Asignar tarea</button></form></Modal>}
 <style>{`.input{width:100%;border-radius:.75rem;border:1px solid rgb(226 232 240);font-size:.875rem}`}</style></div></AdminLayout>
}
function Field({label,children}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase text-slate-500">{label}</span>{children}</label>}
function Mini({label,value}){return <div className="rounded-xl bg-slate-50 p-3 text-center"><p className="text-[10px] uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-800">{value}</p></div>}
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-[80] flex items-center justify-center overflow-y-auto bg-slate-950/60 p-4"><Card className="my-8 w-full max-w-3xl p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onClose}>✕</button></div>{children}</Card></div>}
